framework:
    rate_limiter:
        content_scraping:
            policy: 'fixed_window'
            limit: 100
            interval: '1 minute'
        
        webhook_api:
            policy: 'token_bucket'
            limit: 10
            rate: { interval: '1 minute', amount: 5 }
